### ISSUE TITLE
New release with bug fix

### ISSUE THREAD

**Issue by harpster604** [PaymentRails/php-sdk#10]
I had mentioned a bug to support around mid-June which was promptly fixed in your code base during this commit:
https://github.com/PaymentRails/php-sdk/commit/3f529ed3e60b35ff8261dbbba80f34980bd94799

Just wondering if there will be a tagged release with this fix that we can update through composer? I am not sure if using the master branch of your package on our production server is the best idea since it may be prone to future bugs.

**Comment by fronugget** [comment]
If you don't want to use master, you should be able to use a specific
version like 2.0.4 (latest) or an older version that contains that fix

**Comment by harpster604** [comment]
But 2.0.4 does not contain the fix does it?
https://github.com/PaymentRails/php-sdk/compare/2.0.4...master

**Comment by fronugget** [comment]
You are right it does not contain the fix, for now you can use
paymentrails/php-sdk:2.0.5.x-dev
