### ISSUE TITLE
Unable to iterate over balances

### ISSUE THREAD

**Issue by andy-j-roberts** [PaymentRails/php-sdk#28]
When requesting a list of all balances using Balance::all(), if the result set does not result in pagination, the ResourceCollection returned has null values for the page and records and therefore cannot be iterated over as valid() always returns false.

<img width="867" alt="Screenshot 2023-01-27 at 11 52 41" src="https://user-images.githubusercontent.com/28701971/215080843-671fed25-22c7-4169-a6c2-31425ca6e1f2.png">

**Comment by Aman-Aalam** [comment]
Thanks @andy-j-roberts , looking into it.

**Comment by Aman-Aalam** [comment]
@andy-j-roberts Provided a fix for this which works in our testing.
Would you mind giving it a run in your testing environment please and confirm if it solves your issue?
